language: python
install:
  - pip install -r mysite/requirements.txt

script:
  - black --check .
  - flake8 --max-line-length=88 .
 - coverage run --source='mysite' mysite/manage.py test polls
 
after_scripts:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  region: us-west-2
  app: django-tutorial
  env: django-env
  bucket_name: elasticbeanstalk-us-west-2-290512176394
  on:
    branch: main
